# Get a detailed list of nutrition information for each item from an input text query.

# query (required) - a string containing food or drink items.
# If you wish to calculate a specific quantity, you may prefix a quantity before an item.
# For example, 3 tomatoes or 1lb beef brisket.
# If no quantity is specified, the default quantity is 100 grams. Queries cannot exceed 1500 characters.

# @name CalorieNinjas
GET https://api.calorieninjas.com/v1/nutrition?query=10oz onion and a tomato
x-api-key: 1JrAmMYwM1Bt1y2TDZkllg==41waHLnFeI6m1gnc

### ------------------





# Get Fruits with given nutrition between min and max parameter. At least one query parameter has to be given.
# @name Request Fruits information by nutrition value
GET https://www.fruityvice.com/api/fruit/apple?min=0&max=1000

### ------------------

# Get all Fruits available in the database in a list form.
# @name Request all Fruits
GET https://www.fruityvice.com/api/fruit/all

### ------------------

# Add a new fruit to the database
# @name Add a fruit to the database
PUT https://www.fruityvice.com/api/fruit

{
    "genus": "Fragaria",
    "name": "Strawberry",
    "family": "Rosaceae",
    "order": "Rosales",
    "nutritions": {
        "carbohydrates": 5.5,
        "protein": 0,
        "fat": 0.4,
        "calories": 29,
        "sugar": 5.4
    }
}

### ------------------




# The FoodData Central API provides REST access to FoodData Central (FDC).
# FoodData Central currently limits the number of API requests to a default rate of 1,000 requests per hour per IP address
# API GUIDE: https://app.swaggerhub.com/apis/fdcnal/food-data_central_api/1.0.1

# Returns a paged list of foods, in the 'abridged' format
GET https://api.nal.usda.gov/fdc/v1/foods/list?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF

### ------------------
POST https://api.nal.usda.gov/fdc/v1/foods/list?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF
Content-Type: application/json

{
    "pageSize": 2
}

### ------------------

# Returns a list of foods that matched search (query) keywords
GET https://api.nal.usda.gov/fdc/v1/foods/search?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF&query=Cheddar%20Cheese

### ------------------

POST https://api.nal.usda.gov/fdc/v1/foods/search?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF
Content-Type: application/json

{
  "query": "Ice cream",
  "dataType": ["Branded"],
  "pageSize": 2,
  "sortBy": "fdcId",
  "sortOrder": "desc"
}

### ----------------

# Fetches details for one food item by FDC ID
GET https://api.nal.usda.gov/fdc/v1/food/2057648?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF

### ------------------

# Fetches details for multiple food items using input FDC IDs
POST https://api.nal.usda.gov/fdc/v1/foods?api_key=JU9ViL2Rf0dYov0mXG82QLUeAU0bUEQrI1KfAMBF
Content-Type: application/json

{
  "fdcIds": [
    2057648,
    373052,
    616350
  ],
  "format": "abridged",
  "nutrients": [
    203,
    204,
    205
  ]
}

### ------------------